spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      format_sql: true
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/mylists
    username: user
    password: pass
    driverClassName: org.postgresql.Driver
  jwt:
    token:
      secret: jwtsecure
    accesstoken:
      expired: 6000000
    refreshtoken:
      expired: 172800000